spring:
    application:
        name: spring-data-jpa

    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                default_schema: jwt
                format_sql: true
        show-sql: true

server:
    servlet:
        context-path: /api
