spring:
    application:
        name: spring-data-jpa

    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                default_schema: jwt
                format_sql: true
        show-sql: true

server:
    servlet:
        context-path: /api

jwt:
    secret: ${JWT_SECRET}
    expirationTimeMillis: ${JWT_EXPIRATION_TIME_MILLIS}
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}